FROM node:10.4.1

ENV TZ=America/Sao_Paulo

RUN echo 'America/Sao_Paulo' > /etc/timezone && \
  apt-get update  && \
  mkdir -p /root/.ssh

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD [ "npm", "start" ]